apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe-organization
spec:
  replicas: 1 # 部署userService服务的个数
  selector:
    matchLabels:
      name: fe-organization # pod名称
  template:
    metadata:
      labels:
        name: fe-organization # pod名称
    spec:
      containers:
        - name: fe-organization # 镜像名称
          image: ${DATETIME} # 我们打包的镜像
          imagePullPolicy: Always # 容器拉取规则，Always表示每次都从docker私有仓库registry拉取镜像部署
          ports:
            - containerPort: 80
          env: # 设置容器内环境变量，以下效果为设置容器时间为上海标准时间
            - name: TZ
              value: Asia/Shanghai
          lifecycle:
            postStart:
              exec:
                command:
                - sh
                - -c
                - |
                  sleep 9;
                  nginx -s reload;
          readinessProbe:  # 就绪探针
            failureThreshold: 3
            httpGet:
              path: /
              port: 80
              scheme: HTTP
            initialDelaySeconds: 7
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          livenessProbe:  # 存活探针
            httpGet:
              path: /
              port: 80
              scheme: HTTP
            initialDelaySeconds: 15  # 初始延迟时间
            periodSeconds: 10         # 检查频率
            timeoutSeconds: 1         # 超时时间
            failureThreshold: 3       # 失败重试次数