apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe-merchant-pc
spec:
  replicas: 1 # 部署userService服务的个数
  selector:
    matchLabels:
      name: fe-merchant-pc # pod名称
  template:
    metadata:
      labels:
        name: fe-merchant-pc # pod名称
    spec:
      containers:
        - name: fe-merchant-pc # 镜像名称
          image: ${DATETIME} # 我们打包的镜像
          imagePullPolicy: Always # 容器拉取规则，Always表示每次都从docker私有仓库registry拉取镜像部署
          ports:
            - containerPort: 80
          env: # 设置容器内环境变量，以下效果为设置容器时间为上海标准时间
            - name: TZ
              value: Asia/Shanghai